{ config, pkgs, lib, ... }: {
  imports = [
    /etc/nixos/hardware-configuration.nix # generated by nixos-infect 
    /etc/nixos/networking.nix # generated at runtime by nixos-infect
  ];
  
#  nixpkgs.config.allowUnfree = true;

  nix = {
      package = pkgs.nixUnstable; # or versioned attributes like nix_2_4
      extraOptions = ''
        max-jobs = 1
        experimental-features = nix-command flakes
        trusted-substituters = https://lean4.cachix.org/
        trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= lean4.cachix.org-1:mawtxSxcaiWE24xCXXgh3qnvlTkyU7evRRnGeAhD4Wk=
        allow-import-from-derivation = true
        keep-outputs = true
      '';
  };


  virtualisation = {
    podman = {
      enable = true;
      # Create a `docker` alias for podman,
      # to use it as a drop-in replacement
      dockerCompat = true;
    };
  };

  # virtualisation.docker.enable = true;
  programs.mosh = { enable = true; };
  environment.systemPackages = with pkgs; [ neovim git tmux emacs-nox 
      cowsay fzf sbcl 
    ];
	security.acme = {
		acceptTerms = true;
		email = "siddu.druid@gmail.com";
	};

	networking.firewall.allowedTCPPorts = [ 80 443 ];
	services.thelounge.enable = true;
	services.nginx = {
                enable = true;
                enableReload = true;
                recommendedTlsSettings = true;
                recommendedOptimisation = true;
                recommendedGzipSettings = true;
                recommendedProxySettings = true;

                virtualHosts = {
                        "pixel-druid.com" = { 
				locations."/".root = "/var/bollu.github.io";
				addSSL = true;
				enableACME = true;
			};
			"irc.pixel-druid.com" = {
				locations."/".proxyPass = "http://127.0.0.1:" + (builtins.toString config.services.thelounge.port);
				addSSL = true;
				enableACME = true;
			};
                        # "pixel-druid.com".locations."/".root = /var/bollu.github.io;
                        # the above does not generate a config
                        # WTF
		};
	};
  boot.cleanTmpDir = true;
  networking.hostName = "ubuntu-s-1vcpu-1gb-blr1-01";
  services.openssh.enable = true;
  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwy5IMkH2IqMbDwpWmbg9Z2CETZqvpAe9sL+6G+netUjWlr8qDPVQbbeqthm8Nnu3lr9FRDCQ+wgkqZdFKfN8zCSEhSs036+ywSi3Th/a16UaPcMboRl8AIebL/CHW9i6BQmtYOEpIeEele2KUJ+Us4yQyZeE0boRHUtWstcQlRqBV8OT4mf7eP2OAl6ClxBQwHDhj93DlMyfHGbFtH8Hj2IUHCQDszwBRRYjvdv29QC1SJ1SH0SEn7uyjIHo6E01g5JdQDWc8wtIlcnmPMkCCzrDHKM7sCGm8pvKiyJ37ofaG/Zt6zoJGAmRYdQnkmPMUqFdK7MEP8V6hsCdliXQheuL3Ppjw8nZWlAU8nE4HtAFovgkCmgMGeMs1MffyC8ozoXMCtNUUlQD3guqMy9fBEGCOghHUaD/nyxLu/8TipKik04yY8nE2zf/4hEbAjsSfrZalhCMSrBs1x+LFitA2d5UFexUSN+/+fOZd5mMlAt0KOIJPGCX2IDtldJuPeu0= bollu@DESKTOP-J9URRFN" 
  ];
}
